services:
  postgres:
    image: postgres:17-alpine
    container_name: task-nest-postgresql
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: tasknest
      POSTGRES_PASSWORD: tasknest_secret
      POSTGRES_DB: tasknest
      PGPORT: 5433
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: task-nest-backend
    ports:
      - "4200:4200"
    environment:
      DATABASE_URL: "postgresql://tasknest:tasknest_secret@postgres:5433/tasknest"
      JWT_SECRET: "D*IRNF(@#*)"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pgdata:
